<?php
/**
 * @var $block \Smartmage\Inpost\Block\Adminhtml\InpostMode
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */ ?>
<div class="inpost_shipment-section" data-inposttoken="<?= $block->getGeowidgetToken() ?>"></div>
<?php
$scriptString = <<<script
require(['jquery', 'domReady!','inPostShowModal'], function($) {
    window.inpostMode = '{$block->getInPostMode()}';
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
